#!/usr/bin/env python

import platform

Import("env")
env['SYSTEM'] = platform.system().lower()

# Clone build environment for my module
if env['SYSTEM'] in ['linux', 'darwin']:
  env_module = env.Clone(
    SCONS_CXX_STANDARD='c++20',
    CCFLAGS=['--std=c++20']
  )

elif env['SYSTEM'] == 'windows':
  env_module = env.Clone(
    SCONS_CXX_STANDARD='c++20',
    CCFLAGS=['/std:c++20']
  )


# External library paths
env_module.Append(CPPPATH=["../../../../3rdparty/gmlib/libs/gmconcepts/include"])
env_module.Append(CPPPATH=["../../../../3rdparty/gmlib/include"])
env_module.Append(CPPPATH=["../../../../physengine/include"])

# Specify path to blaze -- on Vesleblaut's Vindauge
#env_module.Append(CPPPATH=["E:/<path-to-system-include-folder (containing blaze folder)>"]) # eg. C:/vcpkg/installed/x64-windows/include
env_module.Append(CPPPATH=["E:/Dev/vcpkg/installed/x64-windows/include"])

# Add source-files for my module
env_module.add_source_files(env_module.modules_sources, "*.cpp")

SConscript("joints/SCsub")
